### ISSUE TITLE
WATCHDOG PROBLEM

### ISSUE THREAD

**Issue by aldoeri** [Lime3DS/Lime3DS#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2\lime3ds-2118-windows-msys2

### Description of Issue

WINDOWS 10 AMD A-10  MISSING VULCAN BUT OPEN GL WORKS FINE

### Expected Behavior

with out errors

### Reproduction Steps

opening lime and then it shows me blue screen after certain time

### Log File

[   2.697040] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[ 171.415691] Frontend <Info> lime_qt/main.cpp:GMainWindow:224: Lime3DS Version: 2118 | HEAD-d05749e
[ 171.481120] Frontend <Info> lime_qt/main.cpp:GMainWindow:239: Host CPU: AMD A10-4600M APU with Radeon(tm) HD Graphics   | AVX | FMA
[ 171.490834] Frontend <Info> lime_qt/main.cpp:GMainWindow:241: Host OS: Windows 10 Version 22H2 (Build 19045.4957)
[ 171.492611] Frontend <Info> lime_qt/main.cpp:GMainWindow:244: Host RAM: 7.47 GiB
[ 171.492629] Frontend <Info> lime_qt/main.cpp:GMainWindow:245: Host Swap: 7.00 GiB
[ 173.921042] Frontend <Error> lime_qt/util/graphics_device_info.cpp:GetVulkanPhysicalDevices:45: Error occured while querying for physical devices: Failed to load Vulkan driver library
[ 174.842421] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:238: Secure1 KeyX missing
[ 174.842433] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:257: Secure2 KeyX missing
[ 174.842475] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:348: Failed to decrypt
[ 174.843190] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:238: Secure1 KeyX missing
[ 174.843200] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:257: Secure2 KeyX missing
[ 174.843213] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:348: Failed to decrypt
[ 174.843833] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:238: Secure1 KeyX missing
[ 174.843845] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:257: Secure2 KeyX missing
[ 174.843858] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:348: Failed to decrypt

### System Configuration

CPU: amd- a-10
GPU/Driver:amd
RAM:8g 
OS:

**Comment by OpenSauce04** [comment]
Please properly describe the issue you are having
